name: Generate Python Binaries
on: workflow_dispatch
jobs:
  generate_python_binaries:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Release Python 3.10
        uses: softprops/action-gh-release@v1
        with:
          name: Python 3.10 latest
          tag_name: ${{ github.ref_name }}
      - name: Release Python 3.11
        uses: softprops/action-gh-release@v1
        with:
          name: Python 3.11 latest
          tag_name: ${{ github.ref_name }}
#       - name: Install Dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
#       - name: Build Python Versions
#         run: |
#           git clone https://github.com/alexsch01/test
#           cd test/.github
#           python3 compile_versions.py
#       - name: Release Python 3.10
#         uses: softprops/action-gh-release@v1
#         with:
#           name: Python 3.10 latest
#           tag_name: ${{ github.ref_name }}
#           files: |
#             test/.github/Python-3.10.tar.xz
#       - name: Release Python 3.11
#         uses: softprops/action-gh-release@v1
#         with:
#           name: Python 3.11 latest
#           tag_name: ${{ github.ref_name }}
#           files: |
#             test/.github/Python-3.11.tar.xz
