name: Generate Python Binaries
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
jobs:
  generate_python_binaries:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
    
      - uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev

      - name: Build Python 3.10
        run: |
          rm -rf pydebian
          git clone https://github.com/alexsch01/pydebian
          cd pydebian/.github
          python3 compile_version.py 3.10

      - name: Release Python 3.10
        uses: softprops/action-gh-release@v1
        with:
          name: Python 3.10
          tag_name: python3.10
          files: |
            pydebian/.github/Python-3.10.tar.xz
          fail_on_unmatched_files: true
            
      - name: Build Python 3.11
        run: |
          rm -rf pydebian
          git clone https://github.com/alexsch01/pydebian
          cd pydebian/.github
          python3 compile_version.py 3.11

      - name: Release Python 3.11
        uses: softprops/action-gh-release@v1
        with:
          name: Python 3.11
          tag_name: python3.11
          files: |
            pydebian/.github/Python-3.11.tar.xz
          fail_on_unmatched_files: true
