name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: rm -rf test && git clone https://github.com/alexsch01/test cd test && && python3 compile_versions.py
